[package]
name = "tileset-comparator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
image = "0.23.14"
clap = { version = "3.1.18", features = ["derive"] }
